dist: trusty
sudo: required
language: cpp
cache:
  - apt
  - pip
addons:
  apt:
    packages:
    - pandoc
    - libboost-all-dev
    - openmpi-bin
    - libopenmpi-dev
    - openssh-client
    - openssh-server
    - libinsighttoolkit3-dev
    - libvtk5.8
    - libvtk5-dev
    - libvtkgdcm2.2
    - libgdcm-tools
    - cmake
    - texlive-latex-base
    - texlive-latex-extra
    - texlive-fonts-recommended
    - texlive-latex-recommended
    - texlive-xetex
    - lmodern
install:
- virtualenv virtualenv
- source virtualenv/bin/activate
- pip install --upgrade pip setuptools wheel
- pip install matplotlib
- python -c 'import sys; print sys.path'
- python 06MPI/figures/efficient.py 06MPI/figures/efficient.png
- gem install liquid -v 3.0.6
- gem install jekyll -v 3.1.6
- gem install redcarpet
script:
- ITK_DIR=/usr/lib/InsightToolkit ./build.sh
after_success:
- ./.travis_publish.sh
