dist: trusty
sudo: required
language: cpp
cache:
  - apt
  - pip
addons:
  apt:
    packages:
    - pandoc
    - libboost-all-dev
    - openmpi-bin
    - libopenmpi-dev
    - openssh-client
    - openssh-server
    - libinsighttoolkit3-dev
    - libvtk5.8
    - libvtk5-dev
    - libvtkgdcm2.2
    - libgdcm-tools
    - cmake
install:
- PATH=$HOME/texlive/bin/x86_64-linux:$PATH
- sudo -H pip install --upgrade pip setuptools wheel
- sudo -H pip install matplotlib
- gem install jekyll
- gem install redcarpet
script:
- ./build.sh
before_install:
- openssl aes-256-cbc -K $encrypted_074e99c4de0f_key -iv $encrypted_074e99c4de0f_iv
  -in deploy_key.enc -out deploy_key -d
- REPO=`git config remote.origin.url`
- SSH_REPO=${REPO/https:\/\/github.com\//git@github.com:}
- eval `ssh-agent -s`
- chmod 600 deploy_key
- ssh-add deploy_key
- mkdir -p $HOME/texlive && curl -L https://github.com/urdh/texlive-blob/releases/download/20150712/texlive.tar.xz
  | tar -JxC $HOME/texlive
- export ITK_DIR=/usr/lib/InsightToolkit
after_success:
- cd _site
- git init
- git checkout -b gh-pages
- git config --global user.email "jamespjh@gmail.com"
- git config --global user.name "Pushed by Travis CI"
- git add .
- git commit -m "Pushed by Travis"
- git remote add origin $SSH_REPO
- git push -f -u origin gh-pages
