dist: trusty
sudo: required
language: cpp
cache:
  - apt
addons:
  apt:
    packages:
    - pandoc
    - libboost-all-dev
    - openmpi-bin
    - libopenmpi-dev
    - openssh-client
    - openssh-server
    - libinsighttoolkit3-dev
    - libinsighttoolkit3.6
    - cmake
install:
- PATH=$HOME/texlive/bin/x86_64-linux:$PATH
- gem install jekyll
- gem install redcarpet
script:
- ./build.sh
before_install:
- openssl aes-256-cbc -K $encrypted_074e99c4de0f_key -iv $encrypted_074e99c4de0f_iv
  -in deploy_key.enc -out deploy_key -d
- REPO=`git config remote.origin.url`
- SSH_REPO=${REPO/https:\/\/github.com\//git@github.com:}
- eval `ssh-agent -s`
- chmod 600 deploy_key
- ssh-add deploy_key
- mkdir -p $HOME/texlive && curl -L https://github.com/urdh/texlive-blob/releases/download/20150712/texlive.tar.xz
  | tar -JxC $HOME/texlive
after_success:
- git checkout -b gh-pages
- git add -f _site
- git config --global user.email "jamespjh@gmail.com"
- git config --global user.name "Pushed by Travis CI"
- git commit -m "Pushed by Travis"
- git push $SSH_REPO `git subtree split --prefix _site gh-pages`:gh-pages --force
